import type { FluxSchema, SelectionSet, TypeDef } from "./ast.js";

const SCALARS = new Set(["String", "Int", "Float", "Boolean", "ID", "Bytes"]);

export function tsTypeOf(typeName: string, isList: boolean, nonNull: boolean, listNonNull: boolean): string {
  let base = SCALARS.has(typeName)
    ? typeName === "Int" || typeName === "Float"
      ? "number"
      : typeName === "Boolean"
        ? "boolean"
        : typeName === "Bytes"
          ? "Uint8Array"
          : "string"
    : typeName;
  if (isList) {
    base = `Array<${base}${listNonNull ? "" : " | null"}>`;
  }
  if (!nonNull) base = `${base} | null`;
  return base;
}

export function generateTypescript(schema: FluxSchema): string {
  const lines: string[] = [];
  lines.push(`// Generated by @flux/idl — do not edit`);
  lines.push(`export const FLUX_PACKAGE = ${JSON.stringify(schema.package)};`);
  lines.push("");

  for (const t of schema.types) {
    lines.push(`export interface ${t.name} {`);
    for (const f of t.fields) {
      const opt = f.nonNull ? "" : "?";
      lines.push(
        `  ${f.name}${opt}: ${tsTypeOf(f.typeName, f.isList, f.nonNull, f.listNonNull)};`,
      );
    }
    lines.push(`}`);
    lines.push("");
  }

  for (const svc of schema.services) {
    lines.push(`export interface ${svc.name}Handler {`);
    for (const rpc of svc.rpcs) {
      if (rpc.streaming) {
        lines.push(
          `  ${rpc.name}(input: ${rpc.input}, ctx?: FluxContext): AsyncIterable<${rpc.output}>;`,
        );
      } else {
        lines.push(
          `  ${rpc.name}(input: ${rpc.input}, ctx?: FluxContext): Promise<${rpc.output}> | ${rpc.output};`,
        );
      }
    }
    lines.push(`}`);
    lines.push("");

    lines.push(`export interface ${svc.name}Client {`);
    for (const rpc of svc.rpcs) {
      if (rpc.streaming) {
        lines.push(
          `  ${rpc.name}(input: ${rpc.input}, select?: SelectionSet): AsyncIterable<PartialDeep<${rpc.output}>>;`,
        );
      } else {
        lines.push(
          `  ${rpc.name}(input: ${rpc.input}, select?: SelectionSet): Promise<PartialDeep<${rpc.output}>>;`,
        );
      }
    }
    lines.push(`}`);
    lines.push("");
  }

  lines.push(`export type SelectionSet = { [field: string]: true | SelectionSet };`);
  lines.push(`export type PartialDeep<T> = { [K in keyof T]?: T[K] extends object ? PartialDeep<T[K]> : T[K] };`);
  lines.push(`export interface FluxContext { headers?: Record<string, string>; roles?: string[]; }`);
  lines.push("");
  lines.push(`export const schemaJson = ${JSON.stringify(schema, null, 2)} as const;`);
  return lines.join("\n");
}

export function typeMap(schema: FluxSchema): Map<string, TypeDef> {
  return new Map(schema.types.map((t) => [t.name, t]));
}

export function canonicalizeSelection(select: SelectionSet): string {
  return JSON.stringify(sortKeys(select));
}

function sortKeys(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortKeys);
  if (value && typeof value === "object") {
    const obj = value as Record<string, unknown>;
    const out: Record<string, unknown> = {};
    for (const k of Object.keys(obj).sort()) out[k] = sortKeys(obj[k]);
    return out;
  }
  return value;
}
